name: Auto Business Generator

on:
  schedule:
    - cron: '0 9 * * *'  # runs daily at 9 AM UTC
  workflow_dispatch:      # allows manual run from Actions tab

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python generator.py

      - name: Commit generated ideas to repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add latest_ideas.json || echo "No file to commit"
          git commit -m "🤖 Auto-update business ideas" || echo "Nothing to commit"
          git push
